# Generated by Django 5.2 on 2025-04-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
