# Generated by Django 5.2 on 2025-04-20 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about yourself'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(choices=[('none', 'No Restrictions'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten Free'), ('dairy_free', 'Dairy Free'), ('nut_free', 'Nut Free'), ('halal', 'Halal'), ('kosher', 'Kosher')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_cuisine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_allergies',
            field=models.TextField(blank=True, help_text='List any food allergies you have'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_order_updates',
            field=models.BooleanField(default=True, help_text='Receive updates about your orders'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_promotional_emails',
            field=models.BooleanField(default=True, help_text='Receive promotional emails and offers'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_sms_notifications',
            field=models.BooleanField(default=False, help_text='Receive SMS notifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Your unique referral code', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spice_preference',
            field=models.IntegerField(choices=[(1, 'Mild'), (2, 'Medium'), (3, 'Spicy'), (4, 'Very Spicy')], default=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Registration'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('order', 'Order Placed'), ('booking', 'Booking Made'), ('review', 'Review Posted'), ('favorite', 'Item Favorited'), ('loyalty', 'Loyalty Activity'), ('address_added', 'Address Added'), ('address_updated', 'Address Updated'), ('address_removed', 'Address Removed'), ('email_verified', 'Email Verified'), ('two_factor_enabled', 'Two-Factor Authentication Enabled'), ('two_factor_disabled', 'Two-Factor Authentication Disabled')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=10)),
                ('name', models.CharField(help_text='Name this address (e.g. Home, Office)', max_length=100)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('menu_item', 'Menu Item'), ('category', 'Category')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Favorite',
                'verbose_name_plural': 'User Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
