# Generated by Django 5.2 on 2025-04-19 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AddField(
            model_name='availability',
            name='effective_end_date',
            field=models.DateField(blank=True, help_text='When this availability stops being effective', null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='effective_start_date',
            field=models.DateField(blank=True, help_text='When this availability starts being effective', null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, help_text='Higher priority availabilities take precedence'),
        ),
        migrations.AddField(
            model_name='availability',
            name='recurring',
            field=models.BooleanField(default=True, help_text='If true, this is a recurring availability'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='List of certifications held by the staff member'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='direct_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='max_consecutive_days',
            field=models.PositiveIntegerField(default=6, help_text='Maximum number of consecutive days to work'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='min_hours_per_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='overtime_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pay_frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='hourly', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='preferred_shifts',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('any', 'Any')], default='any', max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='tax_filing_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married_joint', 'Married Filing Jointly'), ('married_separate', 'Married Filing Separately'), ('head_household', 'Head of Household')], max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='tax_withholdings',
            field=models.PositiveIntegerField(default=0, help_text='Number of withholding allowances'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('acknowledged', 'Acknowledged'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('punctuality_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], null=True)),
                ('attendance_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], null=True)),
                ('job_knowledge_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], null=True)),
                ('work_quality_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], null=True)),
                ('productivity_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], null=True)),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], null=True)),
                ('teamwork_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], null=True)),
                ('initiative_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], null=True)),
                ('adaptability_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], null=True)),
                ('customer_service_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], null=True)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('action_plan', models.TextField(blank=True)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('staff_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requires_improvement_plan', models.BooleanField(default=False)),
                ('eligible_for_promotion', models.BooleanField(default=False)),
                ('eligible_for_raise', models.BooleanField(default=False)),
                ('recommended_raise_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='staffing.staffprofile')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='SchedulingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('preference', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Prefer Not to Work'), (2, 'Prefer Not to Work'), (3, 'Neutral'), (4, 'Prefer to Work'), (5, 'Strongly Prefer to Work')], default=3)),
                ('reason', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_preferences', to='staffing.staffprofile')),
            ],
            options={
                'verbose_name_plural': 'Scheduling Preferences',
                'unique_together': {('staff', 'day_of_week')},
            },
        ),
    ]
