# Generated by Django 5.2 on 2025-04-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.TextField(blank=True, help_text='List of allergens'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Calories per serving', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of ingredients'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='spice_level',
            field=models.IntegerField(choices=[(0, 'Not Spicy'), (1, 'Mild'), (2, 'Medium'), (3, 'Hot'), (4, 'Very Hot')], default=0),
        ),
    ]
