# Generated by Django 5.2 on 2025-04-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_allergens_menuitem_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price for profitability tracking', max_digits=10, null=True),
        ),
    ]
