# Generated by Django 5.2 on 2025-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='carbs_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carbohydrates in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fat_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fat in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fiber_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fiber in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_dairy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_keto_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_low_carb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_nut_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='protein_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Protein in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='serving_size',
            field=models.CharField(blank=True, help_text='Serving size description', max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sodium_mg',
            field=models.PositiveIntegerField(blank=True, help_text='Sodium in milligrams', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sugar_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sugar in grams', max_digits=6, null=True),
        ),
    ]
