# Generated by Django 5.2 on 2025-04-19 18:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivered_at',
            new_name='actual_delivery_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='order',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Special instructions for delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_provider',
            field=models.CharField(blank=True, help_text='Delivery service provider', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='feedback',
            field=models.TextField(blank=True, help_text='Customer feedback about this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_message',
            field=models.TextField(blank=True, help_text='Message to include with gift'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_first_order',
            field=models.BooleanField(default=False, help_text="Whether this is the customer's first order"),
        ),
        migrations.AddField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False, help_text='Whether this order is a gift'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the order'),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_guests',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of guests for dine-in orders'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Actual preparation time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2, help_text='Order priority level'),
        ),
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Customer rating for this order', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional service fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, help_text='Order source (website, app, phone, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='special_request',
            field=models.TextField(blank=True, help_text="Customer's special requests"),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, help_text='Table number for dine-in orders', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customizations',
            field=models.JSONField(blank=True, help_text='JSON field for storing customizations', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount for this item', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Reason for the discount', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Whether this item is free (e.g., promotion)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_voided',
            field=models.BooleanField(default=False, help_text='Whether this item was voided'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='void_reason',
            field=models.CharField(blank=True, help_text='Reason for voiding this item', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('dine_in', 'Dine In')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('bank_transfer', 'Bank Transfer'), ('in_store', 'In-Store Payment')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup/Delivery'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
